# Generated by Django 4.1.1 on 2022-10-12 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='getAddOnes',
            new_name='get_add_ones',
        ),
    ]
