# Generated by Django 4.1.1 on 2022-11-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
