# Generated by Django 4.1.1 on 2022-12-21 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0002_rename_qunatity_order_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.IntegerField(default=0)),
                ('orderTime', models.DateTimeField(auto_now_add=True)),
                ('customerDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.customerdetail')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addOns', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('orderMasterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.ordermaster')),
                ('productsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.product')),
            ],
        ),
    ]
