# Generated by Django 4.1.1 on 2022-10-11 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0002_alter_product_addones_delete_addones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_detail',
            new_name='customer',
        ),
    ]
