# Generated by Django 4.1.1 on 2022-12-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0002_rename_phone_customerdetail_contact_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
