# Generated by Django 4.1.1 on 2022-09-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0002_customerdetail_ingredient_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordertime',
        ),
        migrations.AddField(
            model_name='order',
            name='orderTime',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
