# Generated by Django 4.1.1 on 2022-10-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0003_remove_order_ordertime_order_ordertime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Burger', 'Burger')], default='None', max_length=50)),
            ],
        ),
    ]
