# Generated by Django 4.1.1 on 2022-10-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0003_rename_get_add_ones_order_addones_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='addOnes',
            new_name='addOns',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='addOns',
            new_name='addons',
        ),
    ]
