# Generated by Django 4.1.1 on 2022-12-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0003_ordermaster_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='orderNo',
            field=models.IntegerField(default=10851807290665),
        ),
    ]
