# Generated by Django 4.1.1 on 2022-12-22 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0003_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='price',
            field=models.CharField(default=None, max_length=10000),
            preserve_default=False,
        ),
    ]
