# Generated by Django 4.1.1 on 2022-12-21 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0004_alter_ordermaster_orderno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='orderMasterId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.ordermaster'),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='orderNo',
            field=models.IntegerField(default=51483175226749),
        ),
    ]
