# Generated by Django 4.1.1 on 2022-10-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0004_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Burger', 'Burger'), ('Pizza', 'Pizza'), ('Kacchi', 'Kacchi'), ('Biriyani', 'Biriyani')], default='None', max_length=50),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('in_stock', models.IntegerField(default=0)),
                ('catergory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.category')),
            ],
        ),
    ]
