# Generated by Django 4.1.1 on 2022-12-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0005_alter_orderdetail_ordermasterid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='orderNo',
            field=models.IntegerField(),
        ),
    ]
