# Generated by Django 4.1.1 on 2022-10-03 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0005_alter_category_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catergory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.category'),
        ),
    ]
