# Generated by Django 4.1.1 on 2022-12-21 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0006_alter_ordermaster_orderno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='orderMasterId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.ordermaster'),
        ),
    ]
