# Generated by Django 4.1.1 on 2022-10-03 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0007_alter_product_catergory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='catergory',
            field=models.OneToOneField(choices=[('Burger', 'Burger'), ('Pizza', 'Pizza'), ('Kacchi', 'Kacchi'), ('Biriyani', 'Biriyani')], on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.category'),
        ),
    ]
