# Generated by Django 4.1.1 on 2022-12-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0007_alter_orderdetail_ordermasterid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='orderNo',
            field=models.IntegerField(auto_created=5902946338),
        ),
    ]
