# Generated by Django 4.1.1 on 2022-10-03 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0008_order_products_alter_product_catergory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Burger', 'Burger'), ('Pizza', 'Pizza'), ('Kacchi', 'Kacchi'), ('Biriyani', 'Biriyani')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='catergory',
            field=models.OneToOneField(choices=[('Burger', 'Burger'), ('Pizza', 'Pizza'), ('Kacchi', 'Kacchi'), ('Biriyani', 'Biriyani')], null=True, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.category'),
        ),
    ]
