# Generated by Django 4.1.1 on 2022-10-03 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0009_alter_category_category_alter_product_catergory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.product'),
        ),
    ]
