# Generated by Django 4.1.1 on 2022-12-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0010_alter_ordermaster_orderno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='orderNo',
            field=models.CharField(default=3330943079, max_length=100000000000),
        ),
    ]
