# Generated by Django 4.1.1 on 2023-01-10 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0011_alter_ordermaster_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='delivery_time',
            field=models.CharField(auto_created=True, default=datetime.datetime(2023, 1, 10, 11, 22, 8, 263799), max_length=100),
        ),
    ]
