# Generated by Django 4.1.1 on 2022-10-03 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0011_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catergory',
            field=models.OneToOneField(blank=True, choices=[('Burger', 'Burger'), ('Pizza', 'Pizza'), ('Kacchi', 'Kacchi'), ('Biriyani', 'Biriyani')], null=True, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
