# Generated by Django 4.1.1 on 2022-10-03 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0012_alter_product_catergory_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, choices=[('Burger', 'Burger'), ('Pizza', 'Pizza'), ('Kacchi', 'Kacchi'), ('Biriyani', 'Biriyani')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.product'),
            preserve_default=False,
        ),
    ]
