# Generated by Django 4.1.1 on 2022-12-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0012_alter_orderdetail_addons_alter_orderdetail_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='orderNo',
            field=models.CharField(blank=True, default=4048217410, max_length=100000000000),
        ),
    ]
