# Generated by Django 4.1.1 on 2022-10-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0014_alter_category_category_alter_product_catergory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
