# Generated by Django 4.1.1 on 2022-10-10 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0016_alter_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.IntegerField(default=0)),
                ('catergory', models.OneToOneField(blank=True, choices=[('Burger', 'Burger'), ('Pizza', 'Pizza'), ('Kacchi', 'Kacchi'), ('Biriyani', 'Biriyani')], on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.category')),
                ('ingredient', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.product'),
            preserve_default=False,
        ),
    ]
