# Generated by Django 4.1.1 on 2022-12-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0016_alter_orderdetail_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='orderNo',
            field=models.CharField(auto_created=6124650685, blank=True, max_length=100000000000),
        ),
    ]
