# Generated by Django 4.1.1 on 2022-10-10 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0017_product_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ingredients',
        ),
    ]
