# Generated by Django 4.1.1 on 2022-10-10 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0020_alter_order_products_alter_product_catergory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catergory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.category'),
        ),
    ]
