# Generated by Django 4.1.1 on 2022-10-10 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0021_alter_product_catergory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catergory',
            field=models.ForeignKey(blank=True, choices=[('Burger', 'Burger'), ('Pizza', 'Pizza'), ('Kacchi', 'Kacchi'), ('Biriyani', 'Biriyani')], on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.category'),
        ),
    ]
