# Generated by Django 4.1.1 on 2023-01-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0022_alter_ordermaster_delivery_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='ordermaster',
            name='delivery_time',
            field=models.CharField(editable=False, max_length=1000),
        ),
    ]
