# Generated by Django 4.1.1 on 2023-01-10 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0023_remove_orderdetail_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_ons', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_placed', models.BooleanField(default=False)),
                ('order_confirmed', models.BooleanField(default=False)),
                ('order_preparation', models.BooleanField(default=False)),
                ('out_for_delivery', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='customerdetail',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='total',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='add_ons',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.addons'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='payment_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.paymenttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='add_ons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.addons'),
        ),
    ]
