# Generated by Django 4.1.1 on 2023-01-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0024_addons_orderstatus_paymenttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
