# Generated by Django 4.1.1 on 2022-10-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0024_alter_product_catergory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Burger', 'burger'), ('Pizza', 'pizza')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cheese',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='meat',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='salad',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
