# Generated by Django 4.1.1 on 2023-01-10 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0025_alter_ordermaster_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='order_status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.orderstatus'),
            preserve_default=False,
        ),
    ]
