# Generated by Django 4.1.1 on 2022-10-10 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0025_alter_category_category_alter_ingredient_cheese_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('burger', 'Burger'), ('pizza', 'Pizza')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='catergory',
            field=models.ForeignKey(blank=True, choices=[('burger', 'Burger'), ('pizza', 'Pizza')], on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.category'),
        ),
    ]
