# Generated by Django 4.1.1 on 2022-10-10 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0031_alter_category_category_alter_product_catergory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catergory',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredient',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.ingredient'),
        ),
    ]
