# Generated by Django 4.1.1 on 2022-10-10 06:53

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0034_remove_ingredient_cheese_remove_ingredient_meat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', multiselectfield.db.fields.MultiSelectField(choices=[('salad', 'Salad'), ('cheese', 'Cheese'), ('meat', 'Meat'), ('spice', 'Spice'), ('mayonise', 'Mayonise')], max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredient',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.AddField(
            model_name='product',
            name='addOne',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.addones'),
            preserve_default=False,
        ),
    ]
