# Generated by Django 4.1.1 on 2022-10-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0035_addones_remove_product_ingredient_delete_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('B', 'Burger'), ('P', 'Pizza'), ('C', 'Chicken')], max_length=50),
        ),
    ]
