# Generated by Django 4.1.1 on 2023-01-12 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0036_alter_orderstatus_delivered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatus',
            old_name='order_preparation',
            new_name='order_preparation_on_going',
        ),
    ]
