# Generated by Django 4.1.1 on 2022-10-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0036_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Burger', 'Burger'), ('Pizza', 'Pizza'), ('Chicken', 'Chicken')], max_length=50),
        ),
    ]
