# Generated by Django 4.1.1 on 2023-01-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0037_rename_order_preparation_orderstatus_order_preparation_on_going'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='payment_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
