# Generated by Django 4.1.1 on 2022-10-10 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0037_alter_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addones',
            old_name='ingredient',
            new_name='addOnes',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='addOne',
            new_name='addOnes',
        ),
    ]
