# Generated by Django 4.1.1 on 2023-01-12 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0038_ordermaster_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='price',
        ),
    ]
