# Generated by Django 4.1.1 on 2022-10-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0039_alter_order_price_alter_order_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catergory',
            new_name='category',
        ),
    ]
