# Generated by Django 4.1.1 on 2023-01-12 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0039_remove_orderdetail_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='add_ons',
        ),
        migrations.RemoveField(
            model_name='product',
            name='add_ons',
        ),
        migrations.AddField(
            model_name='addons',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.product'),
            preserve_default=False,
        ),
    ]
