# Generated by Django 4.1.1 on 2023-01-12 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0040_remove_category_add_ons_remove_product_add_ons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addons',
            name='product',
        ),
        migrations.AddField(
            model_name='addons',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.category'),
            preserve_default=False,
        ),
    ]
