# Generated by Django 4.1.1 on 2022-10-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0044_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
