# Generated by Django 4.1.1 on 2022-10-10 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0045_remove_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='addOnes',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.addones'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BurgerApi.category'),
        ),
    ]
