# Generated by Django 4.1.1 on 2022-10-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0050_remove_order_customer_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customerDetail',
        ),
    ]
